# Generated by Django 5.1.4 on 2024-12-16 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('user_credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShippingDetails',
            fields=[
                ('first_name', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.RegexValidator(message='First Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{1,255}$)|(^[A-Za-z]{1,}[\\s\\-]{1}[A-Za-z]{1,253}$)')])),
                ('last_name', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.RegexValidator(message='Last Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{1,255}$)|(^[A-Za-z]{1,}[\\s\\-]{1}[A-Za-z]{1,253}$)')])),
                ('phone_number', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 15 characters'}, max_length=15, validators=[django.core.validators.RegexValidator(message='This field can only contain digits', regex='^[0-9]{7,15}$')])),
                ('street_address', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, apostrophes, and periods, and must start and end with a letter or digit', regex="^([A-Za-z0-9])([A-Za-z0-9\\s\\-\\.\\,']{6,253})([A-Za-z0-9])$")])),
                ('apartment', models.CharField(blank=True, error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 10 characters'}, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, and periods, and must start and end with a letter or digit', regex='^[A-Za-z0-9]([A-Za-z0-9\\s\\-\\.]{0,6}[A-Za-z0-9])?$')])),
                ('postal_code', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 15 characters'}, max_length=15, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, commas, and periods, and must start and end with a letter or digit', regex='^([A-Za-z0-9]{1,})([A-Za-z0-9\\s\\-\\.\\,]{0,12})([A-Za-z0-9]{1})$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_shipping_details', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.region')),
            ],
            options={
                'verbose_name_plural': 'User Shipping Details',
            },
        ),
    ]
