# Generated by Django 5.1.4 on 2024-12-15 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetails',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='First Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{1,255}$)|(^[A-Za-z]{1,}[\\s\\-]{1}[A-Za-z]{1,253}$)')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Last Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{1,255}$)|(^[A-Za-z]{1,}[\\s\\-]{1}[A-Za-z]{1,253}$)')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 15 characters'}, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain digits', regex='^[0-9]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='postal_code',
            field=models.CharField(blank=True, error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 15 characters'}, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, commas, and periods, and must start and end with a letter or digit', regex='^([A-Za-z0-9]{1,})([A-Za-z0-9\\s\\-\\.\\,]{0,12})([A-Za-z0-9]{1})$')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='street_address',
            field=models.CharField(blank=True, error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, apostrophes, and periods, and must start and end with a letter or digit', regex="^([A-Za-z0-9])([A-Za-z0-9\\s\\-\\.\\,']{6,253})([A-Za-z0-9])$")]),
        ),
    ]
