# Generated by Django 5.1.4 on 2024-12-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='region',
        ),
    ]
