# Generated by Django 5.1.4 on 2024-12-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0005_alter_usershippingdetails_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='usershippingdetails',
            name='street_address',
        ),
    ]
