# Generated by Django 5.1.4 on 2024-12-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('user_shipping_details', '0006_remove_usershippingdetails_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingdetails',
            name='country',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country'),
        ),
    ]
