# Generated by Django 5.1.4 on 2024-12-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('user_shipping_details', '0007_usershippingdetails_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingdetails',
            name='city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city'),
        ),
    ]
