# Generated by Django 5.1.4 on 2024-12-16 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('first_name', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{1,255}$)|(^[A-Za-z]{1,}[\\s\\-]{1}[A-Za-z]{1,253}$)')])),
                ('last_name', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{1,255}$)|(^[A-Za-z]{1,}[\\s\\-]{1}[A-Za-z]{1,253}$)')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
